# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: maxchen
email: 
description: Copyright © 2015 - 2016 maxchen. All Rights Reserved
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chenyibo.org" # the base hostname & protocol for your site
twitter_username: 
github_username: 

# Build settings
markdown: kramdown

# Custom settings
permalink: :title
kramdown:
  input: GFM
  hard_wrap: false